language: java
jdk: openjdk11
env:
  global:
  - secure: r/NjDkRmzceu1+pKaEaVkBv1UcesZgOkqswoaYvUnCbx1T+/juE0pQPsg0FjusdAbCjc6+6gIwWpsIEjtXnquS2rZzVaW6Laz6cdLq1Jhqnbdc7w2u5Eax1AWAOopIh7UY0xuaHLji+WsWG7ZRgBSRiuKf0x1Qa0DI5QBUd7L3kbXH2N8mPVeC4rp2xZX+lNEcUn21CgGQZB+oPUeO2meT3Al/6nXVj3Rn+8w2arL+V27oKpepbp5c/96xHJ6WJoK3PXxceBw9Pkuq3A2OG9wVETwO4PUoz9yArBBZ8uFDnRZghJipRfI1oIuutf/40yLYdAZoOwLMy1HtDgBL1BUakIBRNyVufDQVMQrogejRL7I+Dp8US5CxG2b8xFl1iWN7mBOuEbaweyprHipuYt/axa0nLfuqxWSyfSLvwthjeqNFkZQ/SI1vYa4onorHsvh/ibOBrTMiQHMiVCMQOSFxACy2W9z9Yph+S49tIoMtoCQnwESduwOLa53HjuEVK3IbogsE3zHkk/zRFZHO9HuLPu91j4FO8KJorfcSmgtqQt2oZ+XGsrybB6OipTvAyegpDLP+x1uox3S2r4EXz3NGbTxJ3R+R4l4fe880iyIXgWl5MIoUm0qTeT5WxtxODLPFdJBrz80TNSe3vFN3L6wY+N1g7o4B8l8vM5232aYAg=
  - secure: bfq0dRGw30mwQRrrwuzu88+nL2JI/E7GoE2HLsGxRjIPs6+DlR1Bi045TXN/KPKQ7eZmm1nFclDaM+mgQnRyKl7+H+6TSe75xiaxeOhb/wC48QaKRe8PNFLjDsEx9mNiO5jFoWGiICqCAwsFdQEVSDghAv5fHJrNL9j3t4ABBMw1gMT+sxw5lMMVO7uXMh6jDee+VtVAzYzJege5kd6Hb7Lux3PTauux33gRyk24O3JGMu9dd/iT029UBlK09qQ5F397hNa26ndqluWUUlvixlYdXOsyzsV6mUtrKH3zRQ9S3Yh1t+VSWO865EXOa9RyA7GpOtWsUz4/POtkixgWisrkqHC/4FxIQ4WWEsGjFqI7g2IREO/6OWeMqfu/sYvy6yK08UV9CI9YjeuwQSPfWGIvFax0QJop2GOIsfdNeqaSfakf44vEyLqsIAE3JhZqk0qqUrB69NRGel7TXikeu/xrBedOcaFsQ/x9LKkxOT+wB9VjKuheKMtQfmxq3ip0iX99iv2x7sXCPSQIHtGN+2a01sIKg5zOWqMdELU7WLmwz63WwawNAc3wz5mRM+JjFfZ5RHXcvAJ/jKBAD0lz6LgNd1AID+3+NDuY0GDwVwRopShGc/SmUs3CFgwala5Cwwg0hi9CBeX+UKHJZ7qvuP2QniT7wDKC3A8vP9/KAEM=
install: skip
script: mvn --settings .mvn/settings.xml install && ([[ $TRAVIS_BRANCH != "master" ]] || mvn --settings .mvn/settings.xml -DskipTests=true deploy)
sudo: false
cache:
  directories: "$HOME/.m2"
branches:
  except: gh-pages
notifications:
  email: joerg.hohwiller@googlemail.com
