language: java
jdk: openjdk11
env:
  global:
  - secure: VFmWNkkbJ8B2m/FVWhKAAb1lsYYuglaObmOiUnPvk6qy2e1WWBndMz5yEKSxGPcdYu3nzQ9dhfgkFbqPYpm4g5xRAG4jYV/bMVqvt7opbV4TTb0QGaqiSZOsKw4Uu+U7GVmr723A6QVvA7BKUqgIi7NiG9t8xVvkJDLQCBnhDGxu2Kznf/6KlVENMyla8FfBqZ5Z1iSdFwLQIdB9Wf2yYg4NlTk5u/O6TWIBfJ4ljuzDw6vjsU8uZkvlRSH3B1ZwRqpLj6xGgAmrEl6JONCasSv7G368RzWCDGXMen3CgOs3NwLKBZbCjr3tajK5CN8Oqre7Oh+9kGE7Hc+kJ9Y2MqobP3axkrwi3fE0mB6fmyd4HV6UPZbF9g6J7dPyO9RH51roVXa7iKFuQNedTsfoQfg+9ynC7Ejgqzxoi/W8zasEp4cU8ngnBO4wRBEk072PPPRE4fmWy9TyPuGLu6wPTGPXU5evKzZEcSRqAP1SbT09g1GhCLBjbhrZDsuvWLS5Ik2Y9NsI1grqIL0RK1UItQr/3XzOPEMSpRogpnu7TDYoJJdhhjd5dU51nCH/W0+JwcDrmfidsI0RtqhT39jyrgK7lyp2ult7XCJV/gTXBtP/kd/w1XW+w46/8NUgXVZx1yLo//2SwLnq8d+qcDJDz6+Bx6k9ct8nrgbtz+DhOlQ=
  - secure: kpuvaFqI/or5bqa30LNFqFAyZSoo0DK3CHQAP7EHwRjzaQcPDVWYLH568OeIi4ubowIt5fdUkxn9DLAXRu87YElQdVwv2fjCbx5Xrr/0A7gC7lu0vqfOoqxLamQORys552uokEQrxF6mBbz6iyr/xxh53fa8w3bOSi5liyd33zsE/jB5SSD66R66LO4hrsvQDHnzBmWkoRDcav8YG+eyePIBN/xA5DVSOodJOxzIlW6Lw97R4+T97zXxPX4VJj3Av6IgRL0e2wnZQUvFoggFZe2fz46DY1OU1+3/LgIMDyRLVYkinsTiyedCKVW662YwiCm5jpZ5N+BZrmBT9c6QEzBOq73OfHlm9XVDWIZrOX6HCmjOi6CWOyQsitgyMZBjXwQTeu11c/W27g03M8yL0VtdCO4p4efnQgl0BohPmw3p3DMn+PcmKLAZVtmOVCO1gAoc8qPfjLKQKGBrrzjvlZ2Uu4UlM64dlc2QFtU5WqvBYWEmvv2H25jVURhOxuIephjL2aqd0NGnOoFqaVMXZEdz3WoeTnA3F/k/guNRDehs/HwVL6ZF1iUklzpudDCUIlwpz/gKoZ5mAHgeCWqBpJqd6Ov70aSdb42aPl42mC3Km/hQZJ1XBf0VCqn61lEO65jFDFsV6txvAu+UOJ9ErigdBlwedgACtCdqn23fwdg=
install: skip
script: mvn --settings .mvn/settings.xml install && ([[ $TRAVIS_BRANCH != "master" ]] || mvn --settings .mvn/settings.xml -DskipTests=true deploy)
sudo: false
cache:
  directories: "$HOME/.m2"
branches:
  except: gh-pages
notifications:
  email: joerg.hohwiller@googlemail.com
