language: java
jdk: openjdk11
env:
  global:
  - secure: p7Gk1mE4pp3uwt7U+DPHcShZa9czToK7oZM9Y3GrCmCGuLcxd3vRwuPh4/54bic9wvSqQ1/w0IRay23sror5Ne1cX1Y10foSCXXVJpqRZ4NyUwtdcjpavLXskkcImY7/OnLsFrVi1j0lY0B23WfxX2qWQDCU7nMd8XrEtjfd2uuFprTl9RS9tcjn5HAwnLkY9lO6lNtjlmPIehczvbk3Wgl185JF40tGJLBefIuDxh2GJw5tCe9aofI7nsyLS4DK4zAwyhjgwlxTkFZKMR4TUpy7lqDdqH32yv87xRJhDItpAdpApJozUDbzgr05jgyjr/vlSAAEV0fyfNYfErkckfxoA7z5oX8wymrD/q0QYFkgETCDhNRaWShTxncV6XqDFebFjnnr2t0zhw9Dx2yQ86u1mP1JOYW9wX315z5gldssBAw+DACbKu9Wg79gdnEHfcUuKTLTRNJzUBXxc+iUsvFnkh7q0iYv+5r2ZWK4MhbXkas0DHPwYMPh5DxRVKOPwvax0eCaPH/6m5XDl3ZloD0ekUqLmz45zGhHkGKdqDmi/FynRiGpTPdTs4fAa7VytET1Zi0qrNwtA7Ga9YjvkQ7zdupUa0LSM/8uprmS5U3+Aw4Dp5WIwCPgUjx7G9aXVTTic++FYSFC1HkhfkkTBu0ESlQUpRj2T0560poWFLg=
  - secure: dn/EcE4STXTT0XJCB9Pj7bDaCLoPTq+nkE0duwGi7TCiT45Klj66KrmfyFrcoS/+FhAuTvnyGt37uvEsl6gS500g4F6UY+iig0/gnEH9O5KR0mN6mg9KWACI+H/yW2/OccNnCSdMZlBI5m3aywCMZ5UvrhtcRtGmYXPk7PEaqacUIVmoU/ywgxoXAtaH8NJuQdoqnY1QCDvOYhXNpnkzzHz9XC14qLVekMAOe7x9DWXmZ6jbbc+PCaXpvuSAvRXRDQz7xK0U1pEUdvIWPh2j9Vhmnl4ZUHhTWtXVx47WNba1mwSJ0fiCPKELxLjLF/gTJiz8nyflL3Xsk1YEej/DmwvVhhuM7FT0ahyxdSA5ESkJc6V09x6wJcMXEgc2NhMkj2soczdA3nCY9dHlh2NIG9qah3jZqhwlc/fXLn/XTcqz4/CZdnF1VooLUSoc+ePoHbQK5g9lIxObxAe3xYprt9FHsOyhlGrkctyhzQseZRqCiY/t1DS+mDLrXv6v+XTsJW4GiYiwUGEnCxh6b8dppINX6HGMhJmoADS1MxhyfS4OsfYZ7PAjAPmHp8mNwMBqSNbVCKyMLaG5CY24E9+kN/Q/Y/O3+v4mwdYuOOS/vmOMM2JxxPWkM/88piY7cwslo6AErT2fzU+y8/Ow0nrs8eoSoWI6wgOsH0KxlRinsE4=
install: skip
script: mvn --settings .mvn/settings.xml install && ([[ $TRAVIS_BRANCH != "master" ]] || mvn --settings .mvn/settings.xml -DskipTests=true deploy)
sudo: false
cache:
  directories: "$HOME/.m2"
branches:
  except: gh-pages
notifications:
  email: joerg.hohwiller@googlemail.com
