image:https://m-m-m.github.io/logo.svg[logo,width="150",link="https://m-m-m.github.io"]

image:https://img.shields.io/github/license/m-m-m/base.svg?label=License["Apache License, Version 2.0",link=https://github.com/m-m-m/base/blob/master/LICENSE]
image:https://github.com/m-m-m/base/actions/workflows/build.yml/badge.svg["Build Status",link="https://github.com/m-m-m/base/actions/workflows/build.yml"]

= mmm-base

image:https://img.shields.io/maven-central/v/io.github.m-m-m/mmm-base.svg?label=Maven%20Central["Maven Central",link=https://search.maven.org/search?q=g:io.github.m-m-m]
image:https://javadoc.io/badge2/io.github.m-m-m/mmm-base/javadoc.svg["base JavaDoc", link=https://javadoc.io/doc/io.github.m-m-m/mmm-base]

The module `io.github.mmm.base` (artifactId `mmm-base`) provides a minimal set of APIs and utils for general purpose usage.
It is mainly designed for usage in our own project.
If you find something helpful in there, feel free to also reuse it outside of this `m-m-m` project.
However, we intentionally do not want to be tempted to create another "apache-commons-*" here.
So do not expect generic feature requests to be implemented and keep in mind that we might consider doing a breaking API change in future releases (while we try to avoid this when easily possible).

== Features

This library offers the following features:

* `ApplicationException` for exceptions with `UUID`, `code`, and distinction between user and technical errors.
* `CharFilter` interface and implementations
* `Justification` to justify strings
* Placements such as `Alignment`, `Direction`, `Orientation`, etc.
* Converter and parser for `Temporal` values
* `CompareOperator` to compate strings, numbers, temporals, or any other comparable object
* `CaseHelper` to deal with lower/upper case
* etc.

== Usage

Maven Dependency:
```xml
<dependency>
  <groupId>io.github.m-m-m</groupId>
  <artifactId>mmm-base</artifactId>
  <version>${mmm.base.version}</version>
</dependency>
```

Module Dependency:
```java
  requires transitive io.github.mmm.base;
```

= mmm-base-metainfo

image:https://img.shields.io/maven-central/v/io.github.m-m-m/mmm-base-metainfo.svg?label=Maven%20Central["Maven Central",link=https://search.maven.org/search?q=g:io.github.m-m-m]
image:https://javadoc.io/badge2/io.github.m-m-m/mmm-base-metainfo/javadoc.svg["base JavaDoc", link=https://javadoc.io/doc/io.github.m-m-m/mmm-base-metainfo]

The module `io.github.mmm.base.metainfo` (artifactId `mmm-base-metainfo`) provides a minimal set of APIs for dealing with meta-information.

== Features

This library offers the following features:

* `MetaInfo` interface to instantiate and access meta-information.
* `MetaInfos` to annotate meta-information.

== Usage

Maven Dependency:
```xml
<dependency>
  <groupId>io.github.m-m-m</groupId>
  <artifactId>mmm-base-metainfo</artifactId>
  <version>${mmm.base.version}</version>
</dependency>
```

Module Dependency:
```java
  requires transitive io.github.mmm.base.metainfo;
```

= mmm-base-placement

image:https://img.shields.io/maven-central/v/io.github.m-m-m/mmm-base-placement.svg?label=Maven%20Central["Maven Central",link=https://search.maven.org/search?q=g:io.github.m-m-m]
image:https://javadoc.io/badge2/io.github.m-m-m/mmm-base-placement/javadoc.svg["base JavaDoc", link=https://javadoc.io/doc/io.github.m-m-m/mmm-base-placement]

The module `io.github.mmm.base.placement` (artifactId `mmm-base-placement`) provides a enums for placement.

== Features

This library offers the following enums:

* `Alignment` for 2-D alignments.
* `Direction` for 2-D direction.
* `HorizontalAlignment` for horizontal alignment (1-D).
* `Orientation` with `HORIZONTAL` and `VERTICAL`.
* `VerticalAlignment` for vertical alignment (1-D).

== Usage

Maven Dependency:
```xml
<dependency>
  <groupId>io.github.m-m-m</groupId>
  <artifactId>mmm-base-placement</artifactId>
  <version>${mmm.base.version}</version>
</dependency>
```

Module Dependency:
```java
  requires transitive io.github.mmm.base.placement;
```
